// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUK82lqmlgnBOJTOqHjH-q6Jz_db_9Ip0',
    appId: '1:1020173712813:web:6d5549f89073a5c9457524',
    messagingSenderId: '1020173712813',
    projectId: 'login-test-7804f',
    authDomain: 'login-test-7804f.firebaseapp.com',
    storageBucket: 'login-test-7804f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzp_ClYJms0w8fyuQeQWQ3TUgsPEJCag',
    appId: '1:1020173712813:android:32c4032ecf11055f457524',
    messagingSenderId: '1020173712813',
    projectId: 'login-test-7804f',
    storageBucket: 'login-test-7804f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUK82lqmlgnBOJTOqHjH-q6Jz_db_9Ip0',
    appId: '1:1020173712813:web:efe8607d80211269457524',
    messagingSenderId: '1020173712813',
    projectId: 'login-test-7804f',
    authDomain: 'login-test-7804f.firebaseapp.com',
    storageBucket: 'login-test-7804f.firebasestorage.app',
  );
  
}
